### ISSUE TITLE
Push a new version

### ISSUE THREAD

**Issue by pcorpet** [arukoh/orm_adapter-dynamoid#2]
Hi @arukoh , thanks for accepting my fix which was blocking me from using this library. Could you now do a release and update the Gem on RubyGems please?

**Comment by pcorpet** [comment]
Up, @arukoh can you help me here please?

**Comment by arukoh** [comment]
Hi @pcorpet , I’m so so so sorry for not repling sooner.
I pushed the new version. https://rubygems.org/gems/orm_adapter-dynamoid/versions/0.0.2
